
package com.xyauto.oa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeServiceSoap {


    /**
     * 
     * @param domainAccount
     * @param password
     * @return
     *     returns com.xyauto.oa.LoginResult
     */
    @WebMethod(operationName = "Login", action = "http://tempuri.org/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.LoginResponse")
    public LoginResult login(
        @WebParam(name = "domainAccount", targetNamespace = "http://tempuri.org/")
        String domainAccount,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param account
     * @return
     *     returns com.xyauto.oa.Employee
     */
    @WebMethod(operationName = "GetEmployeeByDomainAccount", action = "http://tempuri.org/GetEmployeeByDomainAccount")
    @WebResult(name = "GetEmployeeByDomainAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEmployeeByDomainAccount", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetEmployeeByDomainAccount")
    @ResponseWrapper(localName = "GetEmployeeByDomainAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetEmployeeByDomainAccountResponse")
    public Employee getEmployeeByDomainAccount(
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        String account);

    /**
     * 
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetEmployeeNumberByDomainAccount", action = "http://tempuri.org/GetEmployeeNumberByDomainAccount")
    @WebResult(name = "GetEmployeeNumberByDomainAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEmployeeNumberByDomainAccount", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetEmployeeNumberByDomainAccount")
    @ResponseWrapper(localName = "GetEmployeeNumberByDomainAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetEmployeeNumberByDomainAccountResponse")
    public String getEmployeeNumberByDomainAccount(
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        String account);

    /**
     * 
     * @param employeeNumber
     * @return
     *     returns com.xyauto.oa.Employee
     */
    @WebMethod(operationName = "GetEmployeeByEmployeeNumber", action = "http://tempuri.org/GetEmployeeByEmployeeNumber")
    @WebResult(name = "GetEmployeeByEmployeeNumberResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEmployeeByEmployeeNumber", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetEmployeeByEmployeeNumber")
    @ResponseWrapper(localName = "GetEmployeeByEmployeeNumberResponse", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetEmployeeByEmployeeNumberResponse")
    public Employee getEmployeeByEmployeeNumber(
        @WebParam(name = "employeeNumber", targetNamespace = "http://tempuri.org/")
        String employeeNumber);

    /**
     * 
     * @param keywords
     * @return
     *     returns com.xyauto.oa.ArrayOfEmployee
     */
    @WebMethod(operationName = "QueryEmployeeByCnName", action = "http://tempuri.org/QueryEmployeeByCnName")
    @WebResult(name = "QueryEmployeeByCnNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryEmployeeByCnName", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.QueryEmployeeByCnName")
    @ResponseWrapper(localName = "QueryEmployeeByCnNameResponse", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.QueryEmployeeByCnNameResponse")
    public ArrayOfEmployee queryEmployeeByCnName(
        @WebParam(name = "keywords", targetNamespace = "http://tempuri.org/")
        String keywords);

    /**
     * 
     * @param includeChildren
     * @param filterParttime
     * @param pageIndex
     * @param deptId
     * @param pageSize
     * @param employeeCount
     * @param queryEmployeeByDeptResult
     */
    @WebMethod(operationName = "QueryEmployeeByDept", action = "http://tempuri.org/QueryEmployeeByDept")
    @RequestWrapper(localName = "QueryEmployeeByDept", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.QueryEmployeeByDept")
    @ResponseWrapper(localName = "QueryEmployeeByDeptResponse", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.QueryEmployeeByDeptResponse")
    public void queryEmployeeByDept(
        @WebParam(name = "deptId", targetNamespace = "http://tempuri.org/")
        int deptId,
        @WebParam(name = "includeChildren", targetNamespace = "http://tempuri.org/")
        boolean includeChildren,
        @WebParam(name = "filterParttime", targetNamespace = "http://tempuri.org/")
        boolean filterParttime,
        @WebParam(name = "pageSize", targetNamespace = "http://tempuri.org/")
        int pageSize,
        @WebParam(name = "pageIndex", targetNamespace = "http://tempuri.org/")
        int pageIndex,
        @WebParam(name = "QueryEmployeeByDeptResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfEmployee> queryEmployeeByDeptResult,
        @WebParam(name = "employeeCount", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Integer> employeeCount);

    /**
     * 
     * @param deptName
     * @return
     *     returns com.xyauto.oa.ArrayOfEmployee
     */
    @WebMethod(operationName = "QueryManagerByDeptName", action = "http://tempuri.org/QueryManagerByDeptName")
    @WebResult(name = "QueryManagerByDeptNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryManagerByDeptName", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.QueryManagerByDeptName")
    @ResponseWrapper(localName = "QueryManagerByDeptNameResponse", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.QueryManagerByDeptNameResponse")
    public ArrayOfEmployee queryManagerByDeptName(
        @WebParam(name = "deptName", targetNamespace = "http://tempuri.org/")
        String deptName);

    /**
     * 
     * @param account
     * @return
     *     returns com.xyauto.oa.Department
     */
    @WebMethod(operationName = "GetDeptByEmployee", action = "http://tempuri.org/GetDeptByEmployee")
    @WebResult(name = "GetDeptByEmployeeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDeptByEmployee", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetDeptByEmployee")
    @ResponseWrapper(localName = "GetDeptByEmployeeResponse", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetDeptByEmployeeResponse")
    public Department getDeptByEmployee(
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        String account);

    /**
     * 
     * @param deptName
     * @return
     *     returns com.xyauto.oa.ArrayOfDepartment
     */
    @WebMethod(operationName = "QueryDeptByName", action = "http://tempuri.org/QueryDeptByName")
    @WebResult(name = "QueryDeptByNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryDeptByName", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.QueryDeptByName")
    @ResponseWrapper(localName = "QueryDeptByNameResponse", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.QueryDeptByNameResponse")
    public ArrayOfDepartment queryDeptByName(
        @WebParam(name = "deptName", targetNamespace = "http://tempuri.org/")
        String deptName);

    /**
     * 
     * @param deptId
     * @param includeAll
     * @return
     *     returns com.xyauto.oa.ArrayOfDepartment
     */
    @WebMethod(operationName = "QuerySubDept", action = "http://tempuri.org/QuerySubDept")
    @WebResult(name = "QuerySubDeptResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QuerySubDept", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.QuerySubDept")
    @ResponseWrapper(localName = "QuerySubDeptResponse", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.QuerySubDeptResponse")
    public ArrayOfDepartment querySubDept(
        @WebParam(name = "deptId", targetNamespace = "http://tempuri.org/")
        int deptId,
        @WebParam(name = "includeAll", targetNamespace = "http://tempuri.org/")
        boolean includeAll);

    /**
     * 查询当前在职人员信息表，不包含“高管”字段
     * 
     * @param isQueryDB
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAllEmployeeInfo", action = "http://tempuri.org/GetAllEmployeeInfo")
    @WebResult(name = "GetAllEmployeeInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllEmployeeInfo", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetAllEmployeeInfo")
    @ResponseWrapper(localName = "GetAllEmployeeInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetAllEmployeeInfoResponse")
    public String getAllEmployeeInfo(
        @WebParam(name = "isQueryDB", targetNamespace = "http://tempuri.org/")
        boolean isQueryDB);

    /**
     * 给OA流程系统差旅单需求，调用携程同步人员数据提供接口，获取查询某天增量人员数据
     * 
     * @param date
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetEmployeeChangeDataByDateByCtrip", action = "http://tempuri.org/GetEmployeeChangeDataByDateByCtrip")
    @WebResult(name = "GetEmployeeChangeDataByDateByCtripResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEmployeeChangeDataByDateByCtrip", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetEmployeeChangeDataByDateByCtrip")
    @ResponseWrapper(localName = "GetEmployeeChangeDataByDateByCtripResponse", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetEmployeeChangeDataByDateByCtripResponse")
    public String getEmployeeChangeDataByDateByCtrip(
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar date);

    /**
     * 给微信API提供接口，获取查询某天增量人员数据
     * 
     * @param date
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetEmployeeChangeDataByDate", action = "http://tempuri.org/GetEmployeeChangeDataByDate")
    @WebResult(name = "GetEmployeeChangeDataByDateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEmployeeChangeDataByDate", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetEmployeeChangeDataByDate")
    @ResponseWrapper(localName = "GetEmployeeChangeDataByDateResponse", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetEmployeeChangeDataByDateResponse")
    public String getEmployeeChangeDataByDate(
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar date);

    /**
     * 给微信API提供接口，获取查询某天增量部门数据
     * 
     * @param date
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDeptChangeDataByDate", action = "http://tempuri.org/GetDeptChangeDataByDate")
    @WebResult(name = "GetDeptChangeDataByDateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDeptChangeDataByDate", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetDeptChangeDataByDate")
    @ResponseWrapper(localName = "GetDeptChangeDataByDateResponse", targetNamespace = "http://tempuri.org/", className = "com.xyauto.oa.GetDeptChangeDataByDateResponse")
    public String getDeptChangeDataByDate(
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar date);

}
